---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}-1"
    hostname: zookeeper-1
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - "0.0.0.0:2281:2281/tcp"
      - "0.0.0.0:8080:8080/tcp"
      - "0.0.0.0:7000:7000/tcp"
    networks:
      - name: local
    groups:
      - zookeeper
  - name: "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}-2"
    hostname: zookeeper-2
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - "0.0.0.0:2282:2281/tcp"
      - "0.0.0.0:8081:8080/tcp"
      - "0.0.0.0:7001:7000/tcp"
    networks:
      - name: local
    groups:
      - zookeeper
  - name: "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}-3"
    hostname: zookeeper-3
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - "0.0.0.0:2283:2281/tcp"
      - "0.0.0.0:8082:8080/tcp"
      - "0.0.0.0:7002:7000/tcp"
    networks:
      - name: local
    groups:
      - zookeeper
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_SCENARIO_DIRECTORY}/vault
  env:
    ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION:-3.8.4}
  inventory:
    host_vars:
      "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}-1":
        zookeeper_id: 1
      "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}-2":
        zookeeper_id: 2
      "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}-3":
        zookeeper_id: 3
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint