---
- name: Ensure ps util is installed
  yum:
    name: procps-ng # For zkServer.sh

- name: Ensure {{ zookeeper_group_name }} group exists
  group:
    name: "{{ zookeeper_group_name }}"
    system: yes
  when: zookeeper_create_group

- name: Ensure {{ zookeeper_user_name }} user exists
  user:
    name: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    createhome: no
    system: yes
  when: zookeeper_create_user

- name: Ensure {{ zookeeper_base_dir }} directory exists
  file:
    path: "{{ zookeeper_base_dir }}"
    state: directory
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    mode: "0755"

- name: Download Zookeeper {{ zookeeper_version }} distro
  get_url:
    url: "{{ zookeeper_distro_url }}"
    dest: "{{ zookeeper_base_dir }}/{{ zookeeper_distro_file }}"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"

- name: Unarchive Zookeeper {{ zookeeper_version }} distro
  unarchive:
    src: "{{ zookeeper_base_dir }}/{{ zookeeper_distro_file }}"
    dest: "{{ zookeeper_base_dir }}"
    remote_src: yes
    creates: "{{ zookeeper_base_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"

- name: Ensure required directories exist
  file:
    dest: "{{ item }}"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ zookeeper_log_dir }}"
    - "{{ zookeeper_data_dir }}"

- name: Ensure required symlinks exist
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
  with_items:
    - src: "{{ zookeeper_base_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin"
      dest: "{{ zookeeper_home_dir }}"
    - src: "{{ zookeeper_home_dir }}/conf"
      dest: "{{ zookeeper_conf_dir }}"

- name: Ensure required config files are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    mode: '0644'
  notify:
    - Restart zookeeper service
  with_items:
    - src: zoo.cfg.j2
      dest: "{{ zookeeper_conf_dir }}/zoo.cfg"
    - src: java.env.j2
      dest: "{{ zookeeper_conf_dir }}/java.env"

- name: Ensure myid is set
  copy:
    dest: "{{ zookeeper_data_dir }}/myid"
    content: "{{ zookeeper_id }}"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    mode: '0644'
  notify:
    - Restart zookeeper service

- name: Ensure zookeeper systemd unit is present
  template:
    src: "{{ zookeeper_service_name }}.j2"
    dest: "/etc/systemd/system/{{ zookeeper_service_name }}"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    mode: '0644'

- name: Ensure zookeeper service is {{ zookeeper_service_enabled | ternary('enabled', 'disabled') }} on boot
  systemd:
    name: "{{ zookeeper_service_name }}"
    enabled: "{{ zookeeper_service_enabled | ternary('yes', 'no') }}"

- name: Ensure PATH variable contains {{ zookeeper_home_dir }}/bin directory
  copy:
    dest: "/etc/profile.d/zookeeper.sh"
    content: "export PATH=$PATH:{{ zookeeper_home_dir }}/bin"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    mode: '0644'
