---
- name: Zookeeper SSL configuration
  when:
    - not zookeeper_ssl_trust_store | default('') | string
    - not zookeeper_ssl_key_store | default('') | string
  block:
    - name: Generate Zookeeper server CA key
      # Reasons not to use openssl_privatekey module:
      # - Starting from OpenSSL 1.1.0, the default algorithms in the pkcs8 utility have been changed to PKCS#5 v2.0.
      #   Java does not fully support PKCS#5 v2.0 (https://bugs.openjdk.org/browse/JDK-8076999).
      #   The openssl_privatekey module does not allow you to select a java-supported algorithm because the cipher argument must always be set to auto.
      # - Prior to Ansible 2.10, the openssl_privatekey module had no format argument. We cannot generate a key in pkcs8 format acceptable for java.
      ansible.builtin.shell: >
        set -o pipefail &&
        openssl genrsa 4096 | openssl pkcs8 -topk8 -inform PEM -out {{ zookeeper_ssl_dir }}/server-ca.key
        {% if zookeeper_ssl_trust_store_password %}-passout pass:{{ zookeeper_ssl_trust_store_password }} -v1 PBE-SHA1-3DES{% else %}-nocrypt{% endif %}
        && chown {{ zookeeper_user_name }}:{{ zookeeper_group_name }} {{ zookeeper_ssl_dir }}/server-ca.key
        && chmod 0600 {{ zookeeper_ssl_dir }}/server-ca.key
      args:
        creates: "{{ zookeeper_ssl_dir }}/server-ca.key"

    - name: Generate Zookeeper server CA certificate signing request
      community.crypto.openssl_csr:
        path: "{{ zookeeper_ssl_dir }}/server-ca.csr"
        privatekey_path: "{{ zookeeper_ssl_dir }}/server-ca.key"
        privatekey_passphrase: "{{ zookeeper_ssl_trust_store_password }}"
        use_common_name_for_san: no
        common_name: Zookeeper server CA
        basicConstraints:
          - 'CA:TRUE'
        keyUsage:
          - keyCertSign
        owner: "{{ zookeeper_user_name }}"
        group: "{{ zookeeper_group_name }}"
        mode: "0600"
      run_once: yes

    - name: Generate Zookeeper server CA certificate
      community.crypto.x509_certificate:
        path: "{{ zookeeper_ssl_trust_store_location }}"
        csr_path: "{{ zookeeper_ssl_dir }}/server-ca.csr"
        privatekey_path: "{{ zookeeper_ssl_dir }}/server-ca.key"
        privatekey_passphrase: "{{ zookeeper_ssl_trust_store_password }}"
        provider: selfsigned
        owner: "{{ zookeeper_user_name }}"
        group: "{{ zookeeper_group_name }}"
        mode: "0600"
      run_once: yes

    - name: Read Zookeeper server CA certificate content
      ansible.builtin.slurp:
        src: "{{ zookeeper_ssl_trust_store_location }}"
      run_once: yes
      register: ca_cert

    - name: Read Zookeeper server CA key content
      ansible.builtin.slurp:
        src: "{{ zookeeper_ssl_dir }}/server-ca.key"
      run_once: yes
      register: ca_key

    - name: Distribute Zookeeper server CA certificate and key across all nodes
      ansible.builtin.copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content }}"
        owner: "{{ zookeeper_user_name }}"
        group: "{{ zookeeper_group_name }}"
        mode: "0600"
      with_items:
        - content: "{{ ca_cert.content | b64decode }}"
          dest: "{{ zookeeper_ssl_trust_store_location }}"
        - content: "{{ ca_key.content | b64decode }}"
          dest: "{{ zookeeper_ssl_dir }}/server-ca.key"

    - name: Generate Zookeeper server key
      # Reasons not to use openssl_privatekey module:
      # - Starting from OpenSSL 1.1.0, the default algorithms in the pkcs8 utility have been changed to PKCS#5 v2.0.
      #   Java does not fully support PKCS#5 v2.0 (https://bugs.openjdk.org/browse/JDK-8076999).
      #   The openssl_privatekey module does not allow you to select a java-supported algorithm because the cipher argument must always be set to auto.
      # - Prior to Ansible 2.10, the openssl_privatekey module had no format argument. We cannot generate a key in pkcs8 format acceptable for java.
      ansible.builtin.shell: >
        set -o pipefail &&
        openssl genrsa 4096 | openssl pkcs8 -topk8 -inform PEM -out {{ zookeeper_ssl_dir }}/server.key
        {% if zookeeper_ssl_key_store_password %}-passout pass:{{ zookeeper_ssl_key_store_password }} -v1 PBE-SHA1-3DES{% else %}-nocrypt{% endif %}
        && chown {{ zookeeper_user_name }}:{{ zookeeper_group_name }} {{ zookeeper_ssl_dir }}/server.key
        && chmod 0600 {{ zookeeper_ssl_dir }}/server.key
      args:
        creates: "{{ zookeeper_ssl_dir }}/server.key"

    - name: Generate Zookeeper server certificate signing request 
      community.crypto.openssl_csr:
        path: "{{ zookeeper_ssl_dir }}/server.csr"
        privatekey_path: "{{ zookeeper_ssl_dir }}/server.key"
        privatekey_passphrase: "{{ zookeeper_ssl_key_store_password }}"
        common_name: "{{ ansible_hostname }}"
        subject_alt_name:
          - "DNS:{{ ansible_fqdn }}"
          - "IP:{{ ansible_default_ipv4.address }}"
        owner: "{{ zookeeper_user_name }}"
        group: "{{ zookeeper_group_name }}"
        mode: "0600"

    - name: Generate Zookeeper server certificate
      community.crypto.x509_certificate:
        path: "{{ zookeeper_ssl_dir }}/server.crt"
        privatekey_path: "{{ zookeeper_ssl_dir }}/server.key" 
        privatekey_passphrase: "{{ zookeeper_ssl_key_store_password }}"
        csr_path: "{{ zookeeper_ssl_dir }}/server.csr"
        provider: ownca
        ownca_path: "{{ zookeeper_ssl_trust_store_location }}"
        ownca_privatekey_path: "{{ zookeeper_ssl_dir }}/server-ca.key"
        ownca_privatekey_passphrase: "{{ zookeeper_ssl_trust_store_password }}"
        owner: "{{ zookeeper_user_name }}"
        group: "{{ zookeeper_group_name }}"
        mode: "0600"

    - name: Make key store
      ansible.builtin.shell: >
        cat server.crt server.key > {{ zookeeper_ssl_key_store_location }}
        && chown {{ zookeeper_user_name }}:{{ zookeeper_group_name }} {{ zookeeper_ssl_key_store_location }}
        && chmod 0600 {{ zookeeper_ssl_key_store_location }}
      args:
        chdir: "{{ zookeeper_ssl_dir }}"
        creates: "{{ zookeeper_ssl_key_store_location }}"
      notify:
        - Restart zookeeper service

- name: Ensure SSL certificates are present
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ zookeeper_user_name }}"
    group: "{{ zookeeper_group_name }}"
    mode: "0600"
  with_items:
    - content: "{{ zookeeper_ssl_trust_store }}"
      dest: "{{ zookeeper_ssl_trust_store_location }}"
    - content: "{{ zookeeper_ssl_key_store }}"
      dest: "{{ zookeeper_ssl_key_store_location }}"
  notify:
    - Restart zookeeper service
  when:
    - zookeeper_ssl_trust_store | default('') | string
    - zookeeper_ssl_key_store | default('') | string