---
- name: Restart zookeeper service
  ansible.builtin.systemd:
    name: "{{ zookeeper_service_name }}"
    state: restarted
    daemon_reload: true
  when:
    - zookeeper_service_state == 'started'
    - zookeeper_service_restart_on_change