---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}"
    hostname: zookeeper
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - "0.0.0.0:2181:2181/tcp"
      - "0.0.0.0:8080:8080/tcp"
      - "0.0.0.0:7000:7000/tcp"
    networks:
      - name: local
    groups:
      - zookeeper
provisioner:
  name: ansible
  env:
    ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION:-3.8.4}
  inventory:
    host_vars:
      "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-zookeeper-${ZOOKEEPER_VERSION:-3.8.4}":
        zookeeper_id: 1
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint