---
- name: Verify
  hosts: all
  tasks:
    - name: Create test node
      community.general.znode:
        hosts: '127.0.0.1:2181'
        name: /test-node
        value: test-value
        state: present
      delegate_to: localhost
      run_once: true

    - name: Read test node
      community.general.znode:
        hosts: '127.0.0.1:2181'
        name: /test-node
        op: get
      delegate_to: localhost
      run_once: true

    - name: Delete test node
      community.general.znode:
        hosts: '127.0.0.1:2181'
        name: /test-node
        state: absent
      delegate_to: localhost
      run_once: true