name: Publishing the ansible role to the Ansible Galaxy
on:
  push:
    tags:
      - '*'

jobs:
  galaxy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible

      - name: Import role to the Ansible Galaxy
        run: ansible-galaxy role import --token ${{ secrets.GALAXY_TOKEN }} $(echo ${{ github.repository }} | tr '/' ' ')