on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.8, 3.9]
        zookeeper-version: [3.5.9, 3.6.3, 3.7.0]
        config:
          - image: "centos"
            tag: "7"
          - image: "rockylinux"
            tag: "8"
          - image: "almalinux"
            tag: "8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run tox
        run: tox
        env:
          ANSIBLE_FORCE_COLOR: '1'
          IMAGE: ${{ matrix.config.image }}
          TAG: ${{ matrix.config.tag }}
          ZOOKEEPER_VERSION: ${{ matrix.zookeeper-version }}
